import { cronService } from "../cron/cron.service";
import { FertieService } from "../fertie/fertie.service";

export const initNotificationCron = ():void => {
  /**
   * schedule a cron job to run every day 
   * to send notification to users ... 
   * 
   * ------------------
   * 
   * and notification text must generated by chatgpt ..
   * 
   *  
   */

  console.log('⌛Scheduling notification every day .. ⌛');

  cronService.schedule(
    'notification',
    // '0 0 * * *', // At 00:00 AM every day'
     '*/2 * * * *', // every minute for testing
    "This will run every minute for testing", // additional message
    sendNotificationByChatGpt
  )}

/**
 * 
 * may be we dont need send notification by cron job..  
 */
export const sendNotificationByChatGpt = async (): Promise<void> => {
  try{

    console.log('Running cron job: sendNotificationByChatGpt');
    
    // Get the current date
    const currentDate = new Date();
    
    // Generate notification from chatgpt ... 

    // first we need to get the users current months all information .. 
    // like ⚡predictedPeriodStart ⚡ predictedPeriodEnd
    // ⚡ predictedOvulationDate ⚡ fertileWindow

     let data = await new FertieService().predictAllDates(userId);

  }catch(error){
     console.error('Error in cron job sendNotificationByChatGpt from :', error);
  }
}